
services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      MYSQL_URL: ${MYSQL_URL}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_JWT_SECRET: ${SPRING_JWT_SECRET}
    networks:
      - mynet
    restart: always

networks:
  mynet:
    external: true
