version: '3'

services:
  springboot-app:
    image: ${DOCKER_USERNAME}/jwt-app:latest
    container_name: jwt_app
    ports:
      - "8080:8080"
    environment:
      SPRING_JWT_SECRET: ${SPRING_JWT_SECRET}
      MYSQL_URL: ${MYSQL_URL}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - mynet
    depends_on:
      - dummy_mysql

  dummy_mysql:
    image: alpine
    command: sleep 10
    networks:
      - mynet

networks:
  mynet:
    external: true
